"""add follows table

Revision ID: dfd45601f9e6
Revises: 3d8788ddbee6
Create Date: 2026-06-22 20:15:38.916943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd45601f9e6'
down_revision: Union[str, Sequence[str], None] = '3d8788ddbee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_following_id'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_id'))
        batch_op.drop_index(batch_op.f('ix_follows_following_id'))
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))

    op.drop_table('follows')
    # ### end Alembic commands ###
